# Generated by Django 5.2.1 on 2025-05-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cursodisciplina_ocorrencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursodisciplina',
            name='periodo',
            field=models.CharField(default=1, max_length=20, verbose_name='Período'),
            preserve_default=False,
        ),
    ]
